### ISSUE TITLE
Add minimal docker compose

### ISSUE THREAD

**Issue by plsnp** [docker-library/hello-world#100]
hello world is nice minimal example for a Dockerfile. Could the most minimal file for docker-compose be added too ?

**Comment by tianon** [comment]
Unfortunately, for a `docker-compose` example to be useful, it needs a container which will stay running (and the `hello-world` container exits immediately).  I would suggest looking at something like [the `wordpress` example](https://hub.docker.com/_/wordpress) if you want a fairly small example that's going to be pretty representative of the general format.

**Comment by plsnp** [comment]
@tianon  this one ? https://github.com/docker-library/wordpress/blob/master/latest/php8.1/fpm/Dockerfile

**Comment by tianon** [comment]
No, that's the `Dockerfile` -- I meant https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose / https://github.com/docker-library/docs/blob/master/wordpress/stack.yml
