### ISSUE TITLE
Equivalent image for debugging, which doesn't exit

### ISSUE THREAD

**Issue by lonix1** [docker-library/hello-world#108]
This is the official, tiny and dead-simple "hello world" image for docker, with 1B+ downloads, so  I hope it's ok to post here. Everyone knows about this image, and uses it for quick debugging.

Is there an equivalent official tiny image that doesn't exit - i.e. doesn't do anything, just stays running until stopped?

**Comment by yosifkit** [comment]
As far as from Docker Official Images, I think most users would use `alpine` or `busybox` to run a very long `sleep` command or similar process.

Outside of official images, there is the incredibly tiny image of Tianon's ["Sleeping Beauty"](https://hub.docker.com/r/tianon/sleeping-beauty).
