### ISSUE TITLE
hello-world will not even run

### ISSUE THREAD

**Issue by jwilleke** [docker-library/hello-world#117]
When trying to get the simplest of things working on an "Docker Official Image" and it fails.

[hello-world](https://hub.docker.com/_/hello-world)

The image will not start.

- Docker desktop Version: 4.30.0 (149282)
- Engine: 26.1.1
- Compose: v2.27.0-desktop.2

Also tried as a pod in Kubernetes.

**Comment by LaurentGoderre** [comment]
Can you provide the error you get?

**Comment by jwilleke** [comment]
Well apparently it runs and terminates. I never see an error.

**Comment by LaurentGoderre** [comment]
I'm pretty sure for this image it's normal. It runs which outputs and then the container stops when the process stops.

**Comment by jwilleke** [comment]
Thanks
You maybe right but as a "Hello World" then it is pretty confusing an useless.

I have been looking for a **very simple** "Hello World" app, deployed by kustomize, that is known to work to use for troubleshooting issues in a cluster.

Have yet to find one.

**Comment by yosifkit** [comment]
Yeah, this image is really just a "cli" that prints output and exits. If you want something that responds to network and stays up, then an empty/unconfigured `nginx` would work pretty well.  But if you need something a little more complex there is a simple voting app: https://github.com/dockersamples/example-voting-app.
