### ISSUE TITLE
Docker images pull issue 

### ISSUE THREAD

**Issue by addprs** [docker-library/hello-world#18]
latest: Pulling from library/hello-world
c04b14da8d14: Pulling fs layer 
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1469123936&Signature=RZW6qVY3UOC1blHredNDGo4cTRClGIWPUwWVBCknaSc4h9SyRHZL0GVrHkFroA6LXofnWKr2oj4qQ2HAmSG3XLNkoJbYkJI6D3RVGdG79n1v-wlAwFrH1tbGiVa2WgNb~PBIMA5y9~ToY5wywDztf7T73HA5T0RCfEkQ2T5Pygs_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: x509: certificate signed by unknown authority

**Comment by yosifkit** [comment]
This is an issue with the Docker Hub and not a problem with the content of the official image. I think you can report hub issues on the [forums](https://forums.docker.com/) or one of the other places listed on the [help page](https://hub.docker.com/help/).
