### ISSUE TITLE
standard_init_linux.go:175: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by liuxiaopiao** [docker-library/hello-world#19]
I can run other images successfully but when running the hello-world, it fails:

[root@vm ~]# docker run hello-world
standard_init_linux.go:175: exec user process caused "permission denied"

**And my docker info is like below:**
[root@vm ~]# docker info
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 3
Server Version: 1.12.0-rc5
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.1.12-37.6.1.el7uek.x86_64
Operating System: Oracle Linux Server 7.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.135 GiB
Name: slc00bpv.us.oracle.com
ID: QY4D:Q26Y:RHTS:QNUR:NEKC:LSBB:LPR7:ECKG:DRID:EQPJ:3MHG:Z5K6
Docker Root Dir: /scratch/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://www-proxy.us.oracle.com:80
Https Proxy: http://www-proxy.us.oracle.com:80
No Proxy: localhost,127.0.0.0/8,.us.oracle.com,.oraclecorp.com,/var/run/docker.sock
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 dte.docker.oraclecorp.com
 127.0.0.0/8

**And my vm info is**

[root@vm ~]# uname -a
Linux vm 4.1.12-37.6.1.el7uek.x86_64 #2 SMP Thu Jul 28 10:59:49 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

Could you please help me on this?

**Comment by tianon** [comment]
Usually when I see that error it's AppArmor or SELinux or something like that blocking the executable from starting up.

**Comment by liuxiaopiao** [comment]
Thanks @tianon.  Do you have any suggestion that I can do it accordingly to fix this problem?

**Comment by jcf** [comment]
I'm seeing the same issue with Arch Linux, and I'm not using AppArmor or SELinux.

```
$ docker info
Containers: 26
 Running: 0
 Paused: 0
 Stopped: 26
Images: 3
Server Version: 1.12.3
Storage Driver: btrfs
 Build Version: Btrfs v4.8.2
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 125.9 GiB
Name: op
ID: I7AS:7QQG:AOAF:V7WJ:YI6N:3BU6:VXFM:QGNT:SVDW:G62T:RASE:OIJO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

```
$ uname -a
Linux op 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux
```

I'm not sure if this is related to https://github.com/docker/docker/issues/26495.

**Comment by solomonbstoner** [comment]
Hi. I had the same problem. Running `sudo docker run hello-world` fixed my problem. Perhaps it could solve yours too.
The link below holds the solution.
https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
Hope I'm able to help :)

**Comment by wglambert** [comment]
It seems that this was an old issue affecting docker, typically being SELinux related or mounting a filsesystem with the NOEXEC flag
