### ISSUE TITLE
how can I download a docker cert?

### ISSUE THREAD

**Issue by alicepancamo** [docker-library/hello-world#21]
I am having trouble getting to the hub so I can download containers.
Can I do this externally or can a cert be provided.  I am running RHEL 7.2 and firewall is disabled.

Error:
[root@localhost log]# docker run hello-world
Unable to find image 'hello-world:latest' locally
Trying to pull repository registry.access.redhat.com/hello-world ...
unknown: Not Found
Trying to pull repository docker.io/library/hello-world ...
Pulling repository docker.io/library/hello-world
Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority.
See '/usr/bin/docker-current run --help'.
[root@localhost log]#

I have read several articles about this, and I think getting a cert would be the easiest.
Is that possible?

Thanks
Alice

**Comment by tianon** [comment]
This is a generic issue with your Docker installation, and not something specific to this image, so I'm closing this.  I'd recommend asking in either the `#docker` channel on the Freenode IRC network or [on the Docker Forums](https://forums.docker.com/) for help working around your issue. :+1:
