### ISSUE TITLE
Ubuntu 16.14 (Xenial) not allowing to run hello-word with Client.timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by NataliaDiaz** [docker-library/hello-world#28]
It seems I have installed Docker for ubuntu properly, as I can see the help menu when invoking docker. However, when I run:

sudo docker run hello-world
I get:

Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

Also, if I try instead a prebuilt docker image for using ROS Indigo on Ubuntu Xenial with
https://github.com/jbohren/rosdocked
Then I get similar error, what can it be? See command and error below:

sudo ./build.sh ros_docker_image
Sending build context to Docker daemon 84.48 kB
Step 1/19 : FROM ros:indigo
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Any hints?

**Comment by NataliaDiaz** [comment]
Also, if I try instead a prebuilt docker image for using ROS Indigo on Ubuntu Xenial with 
https://github.com/jbohren/rosdocked
Then I get similar error, what can it be? See command and error below: 

sudo ./build.sh ros_docker_image
Sending build context to Docker daemon 84.48 kB
Step 1/19 : FROM ros:indigo
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by yosifkit** [comment]
That sounds like the Docker daemon can't get to the internet , so it can't download any images.  Are you behind a firewall and need an http proxy?

**Comment by NataliaDiaz** [comment]
right, using proxy, that was it!

**Comment by yosifkit** [comment]
Awesome! Glad you got it working.

**Comment by ruslanguns** [comment]
@NataliaDiaz I know this is not a forum, but could you explain a little bit your solution? thanks in advance!

**Comment by NataliaDiaz** [comment]
Under the univ. proxy I had trouble and getting many messages such as (Client.Timeout exceeded while awaiting headers)
Apart from setting the proxy variables in your bash profile such as https_proxy and http_proxy, using sudo -E before every problematic command with such message above, forces to have all env. variables visibles for the proxy too and normally solves the problem.
