### ISSUE TITLE
are you trying to connect to a tls-enabled daemon without tls

### ISSUE THREAD

**Issue by dumplings29** [docker-library/hello-world#3]
after executing $ sudo docker run hello-world that I get this message: 
FATA[0000] post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker .sock: no such file or directory. are you trying to connect to a TLS-enabled daemon without TLS?

How can I do?? help me

**Comment by yosifkit** [comment]
Can you give a little more info?  Are you running boot2docker on a Mac or is this on an ubuntu or other Linux machine?

**Comment by Pherserk** [comment]
Same issue, ubuntu 14.04

**Comment by t-my** [comment]
Fresh Ubuntu 14.04.2, followed instructions from http://docs.docker.com/installation/ubuntulinux/ and got same error message.

**Comment by deserat** [comment]
same issue fresh 14.04

**Comment by tianon** [comment]
This sounds like the Docker daemon isn't even starting up.  Have you checked the daemon logs?  If you're on 14.04, they're probably going to be in `/var/log/upstart/docker.log`.  Regardless, I'm afraid to say that this isn't really an issue with the `hello-world` image (which is what this repository is), and is a general Docker issue.  I would suggest posting on https://groups.google.com/d/forum/docker-user for help with troubleshooting.

**Comment by Nino-K** [comment]
You need to start the docker daemon `sudo start docker` under `/etc/init.d`.

**Comment by dumplings29** [comment]
thanks everyone, let me try

**Comment by rsawankumar** [comment]
thanks,
"sudo start docker" worked for me

**Comment by yssharma** [comment]
Restart box if Ubuntu packages have been updated. And "sudo start docker" works !!

**Comment by eKatsarski** [comment]
xubuntu user here: I was missing apparmor
after i tried what was listed here, this post helped me http://www.tekhead.org/blog/2014/09/installing-docker-on-ubuntu-quick-fix/

**Comment by renatomefidf** [comment]
For those using systemd (fedora, centos, redhat, arch, etc...) you should start it running:

```
#systemctl start docker.service
```

If you want it to start automatically you can run:
```
#systemctl enable docker.service
```

**Comment by declanqian** [comment]
I posted an answer here http://stackoverflow.com/a/30701713/1441295. It may help someone.

**Comment by adam-beck** [comment]
If you are on **Ubuntu 15.04** I believe upstart is being replaced by systemd. Someone can correct me on this at this information is way outside my area of expertise. But, in order to start the docker service you will need to take @renatomefidf's advice. Use `systemctl` to start the docker service.

**Comment by xianlin** [comment]
Another possbile reason is that your bios CPU visualization is not enabled. Go and enable it first!

**Comment by cverbiest** [comment]
add

sudo service docker start
before step 4. works on Redhat RHEL
