### ISSUE TITLE
Probably should target cmd

### ISSUE THREAD

**Issue by jhowardmsft** [docker-library/hello-world#35]
https://github.com/docker-library/hello-world/blob/7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87/amd64/hello-world/nanoserver/hello.txt#L14

In the light of RS3 powershell removal...

**Comment by yosifkit** [comment]
Since upcoming `nanoserver` won't have `powershell` that sounds reasonable, but in that case I'd rather just swap to `windowsservercore` and retain `powershell` to keep it closer in familiarity and usefulness like the `ubuntu` example given in the Linux `hello-world`.
