### ISSUE TITLE
Hello world fails to set itself up while more complicated containers work fine

### ISSUE THREAD

**Issue by bobprime** [docker-library/hello-world#4]
Running `docker run hello-world` fails while it is setting itself up but I can easily run things like library/postgres:9.3 and other complicated containers.  Error follows:

[rwm972@rwm972-1 docker]$ docker -D run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from docker.io/hello-world
a8219747be10: Pull complete 
91c95931e552: Already exists 
docker.io/hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
Status: Downloaded newer image for docker.io/hello-world:latest
DEBU[0004] framesize: 11                                
Timestamp: DEBU[0004] framesize: 1154                              
2015-04-30 10:56:53.775232006 -0400 EDT
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/639334c2fcd5e2c8c2b70923f0c23c90d1557973fcd48c595d47965970474eb6748690236/_tmp.tar -C /var/lib/docker/btrfs/subvolumes/639334c2fcd5e2c8c2b70923f0c23c90d1557973fcd48c595d47965970474eb6/tmp .] failed: /usr/bin/tar: /var/lib/docker/btrfs/subvolumes/639334c2fcd5e2c8c2b70923f0c23c90d1557973fcd48c595d47965970474eb6/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
\---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
\---
1: Init
Package: github.com/docker/libcontainer.(\*linuxStandardInit)
File: standard_init_linux.go@52
\---
2: StartInitialization
Package: github.com/docker/libcontainer.(\*LinuxFactory)
File: factory_linux.go@223
\---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
\---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
\---
5: main
Package: main
File: docker.go@29
\---
6: main
Package: runtime
File: proc.go@63
\---
7: goexit
Package: runtime
File: asm_amd64.s@2232
DEBU[0004] Corrupted prefix: []                         
DEBU[0004] [hijack] End of stdout                       
DEBU[0004] End of CmdRun(), Waiting for hijack to finish. 
FATA[0004] Error response from daemon: : exit status 2  
[rwm972@rwm972-1 docker]$

**Comment by angelamancini** [comment]
I am having the same issue. Running docker on centos 7 vagrant image

**Comment by xiuni** [comment]
I met the same problem, and I reinstalled the docker, it seems no help.

BTW: The system is centos 7.

Thanks!
Brs

**Comment by eandersons** [comment]
Same issue here using CentOS 7.

**Comment by shenyeqing** [comment]
+1 same issue on CentOS7,not only hello-world, some others got the same issue like : docker ui ,shipyard.

**Comment by eandersons** [comment]
I think I found solution for this issue.
As it seems, *Docker* available in *yum* repository is not the latest, so I had to manually upgrade *Docker* binary following [instructions](http://stackoverflow.com/a/26472937). After that everything was working fine.

**Comment by xiuni** [comment]
@eandersons 
Thanks, your solution works well.

**Comment by tianon** [comment]
Closing as this is an issue in Docker, not in the `hello-world` image.  Please direct further debugging / questions to either [the `docker-user` mailing list](https://groups.google.com/d/forum/docker-user) or the `#docker` IRC channel on the [Freenode](https://freenode.net/) network.

**Comment by brouberol** [comment]
I also encountered this issue with docker 1.6.0 running on a Fedora 22. Uninstalling the yum/dnf docker, and re-installing it following [these instructions](https://docs.docker.com/installation/fedora/) fixed it for me.

**Comment by jayunit100** [comment]
I found just re-running `yum install -y --enable-repo=updates-testing docker-io` fixed the issue.
