### ISSUE TITLE
Add Windows Server 2019/RS5 to hello-world

### ISSUE THREAD

**Issue by carlfischer1** [docker-library/hello-world#53]
library/hello-world currently support Windows Server 2016, 1709, and 1803.

Windows Server 2019 aka RS5 was (re-)released in November. The build number to reference is `10.0.17763.1`

The same build number will enable support for the semi-annual channel Windows Server 1809 release.

**Comment by tianon** [comment]
See also my recent comment on https://github.com/docker-library/golang/pull/257#issuecomment-449772799. :disappointed:

**Comment by carlfischer1** [comment]
Manually verified on Server 2019 `10.0.17763.107`
