### ISSUE TITLE
No image description in Dockerhub

### ISSUE THREAD

**Issue by buleoer** [docker-library/hello-world#59]
at https://hub.docker.com/_/hello-world
"There is no available description for this repository."

**Comment by tianon** [comment]
If you go to https://hub.docker.com/v2/repositories/library/hello-world/, you can see that `full_description` includes the appropriate markdown from https://github.com/docker-library/docs/blob/master/hello-world/README.md, so this looks like a Docker Hub JavaScript/rendering issue. :disappointed:

**Comment by tianon** [comment]
I believe issues on https://github.com/docker/hub-feedback are monitored -- it's likely worth filing an issue there (if one does not already exist).

**Comment by wglambert** [comment]
https://github.com/docker/hub-feedback/issues/1867#issuecomment-523702149
>This is fixed now.
