### ISSUE TITLE
ARM compatible version of this hello-world image?

### ISSUE THREAD

**Issue by Govinda-Fichtner** [docker-library/hello-world#7]
When running the `make test-integration-cli` on ARM this hello-world Docker image is used from the Dockerhub.

It fails with the following error:
```
Docker daemon 2.048 kB\rSending build context to Docker daemon 2.048 kB\r\r\nStep 1 : FROM hello-world:frozen\n ---> 91c95931e552\nStep 2 : RUN /hello\n ---> Running in 0b36a68d0e07\n\x1b[91mexec format error\n\x1b[0m[8] System error: exec format error\n"
```

It seems that the binary needs to be made specifically for the armhf architecture.

Made a first draft of an armhf compatible hello-world image here: https://github.com/hypriot/armhf-hello-world

The question is, if this should be merged with this repo or if it should remain separate?

**Comment by tianon** [comment]
Sorry for the seriously long tail on this response. :disappointed:

As we've done elsewhere, I think keeping multiarch deliberate separate for now still makes sense, especially given that we don't officially support multiarch yet.  It's probably worth noting that the image we've pushed at `armhf/hello-world` now comes from https://github.com/tianon/jenkins-groovy/blob/master/dsl/docker-multiarch/images/hello.groovy, which converts the ASM file here directly into a very minimal C file (which allows that script to easily support the breadth of arches, ie `armel/hello-world`, `armhf/hello-world`, `aarch64/hello-world`, `ppc64le/hello-world`, `s390x/hello-world`)

**Comment by ncopa** [comment]
I added a suggestion how to do it in C without "wasting" too much space. It is 1420 bytes so it will increase size with 48%

**Comment by tianon** [comment]
If you look at https://github.com/tianon/jenkins-groovy/blob/master/dsl/docker-multiarch/images/hello.groovy, I've already got it converting to C easily without anything additional here (parsing the message directly from the ASM file and adding the relevant wrapping bits to create the binary for other arches).

**Comment by ncopa** [comment]
I saw it and felt motivated to propose a patch that would break it :)

I don't know what to say about the idea of using groovy to execute (buggy) awk code to parse assembly code to generate C code. Feels a bit upside down to me.

The generated static binary can be significantly smaller too.

**Comment by tianon** [comment]
If the awk code has bugs, I'm very, very interested in fixing them, and in optimizing the C generated there to make smaller binaries.

In the context of this repo however, we do not officially support multiple architectures, so I still think a static ASM binary is a more interesting example use-case to keep in the library.

**Comment by ncopa** [comment]
As I did in the proposed C file, use write(2) instead of printf(3). Thats what the assembly code does too. Then exclude the crt1.o by compiling with `-nostartfiles`, which mean that you need to call exit instead of just return. (thats also what assembly code does). Finally, strip stuff from the generated elf file that you don't really need. It probably makes a difference to use musl C instead of gnu libc too.

awk code will break if you change the asm code like comment out a text line. But I guess that the asm is not supposed to be touched.

**Comment by tianon** [comment]
https://github.com/docker-library/hello-world/commit/a2654a926677e91e30a233758e23b9acb2ef1ea8#diff-e0aaf1f93a44d6d87eac336044ce680b is a definite case of egg-on-my-face here :pensive: :disappointed:

I'll take a look at #9. :innocent: :heart:
