### ISSUE TITLE
make it a non-root container

### ISSUE THREAD

**Issue by fireba11** [docker-library/hello-world#75]
Hm, maybe offer a non-root version? Or put a note somewhere, I was wondering ahy my first try to deploy on my shiny new kubernetes cluster doesn't work for quite a while :-D

**Comment by tianon** [comment]
I'm not sure what you mean -- the `hello-world` image is not something you can easily "run" on Kubernetes (unless you just mean a simple `kubectl run`), because it isn't a persistent service but rather is a simple binary that prints a message and then exits.  There's also no reason it can't run as non-root:

```console
$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest

$ docker run --rm --user 1234:5678 hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

```

**Comment by fireba11** [comment]
I agree that trying that didn't make any sense. I claim lack of sleep ...
Note: The kubernetes error claimed it was a root container. It probably got confused ;-)

**Comment by MPParsley** [comment]
The hello-world container should not run as root;

By default, Docker runs commands inside the container as root which violates the [Principle of Least Privilege (PoLP)](https://en.wikipedia.org/wiki/Principle_of_least_privilege) when superuser permissions are not strictly required. You want to run the container as an unprivileged user whenever possible.
