### ISSUE TITLE
error in macro expansion for DOCKER_GREETING variable

### ISSUE THREAD

**Issue by caryo** [docker-library/hello-world#78]
```
$ git version
git version 2.28.0.windows.1

```

```
$ git log -1
commit 9ef4804c28679a416a445397f9b2e2b105005151 (HEAD -> master, origin/master, origin/HEAD)
Merge: eff5b9a bf64724
Author: yosifkit <yosifkit@gmail.com>
Date:   Tue Apr 28 18:13:18 2020 -0700

    Merge pull request #73 from docker-library/github-actions

    Add initial GitHub Actions CI

```

```
$ docker --version
Docker version 19.03.12, build 48a66213fe


```

```
$ docker build -t hello-world -f Dockerfile.build .

<snip>
Step 7/16 : RUN set -ex;        make clean all test             TARGET_ARCH='amd64'          CROSS_COMPILE='x86_64-linux-gnu-'
 ---> Running in 1773fb3468c3
+ make clean all test TARGET_ARCH=amd64 CROSS_COMPILE=x86_64-linux-gnu-
rm -vrf amd64/hello-world/hello /usr/src/hello/musl/amd64
mkdir -p '/usr/src/hello/musl/amd64'
cd '/usr/src/hello/musl/amd64' && '/usr/local/src/musl/configure' --disable-shared --prefix='/usr/src/hello/musl/amd64/prefix' > /dev/null
make -C '/usr/src/hello/musl/amd64' -j '2' install > /dev/null
/usr/src/hello/musl/amd64/prefix/bin/musl-gcc -Os -fdata-sections -ffunction-sections -s -Wl,--gc-sections -static \
        -o 'amd64/hello-world/hello' \
        -D DOCKER_IMAGE='"hello-world"' \
        -D DOCKER_GREETING="\"$(cat 'greetings/hello-world.txt')\"" \
        -D DOCKER_ARCH='"amd64"' \
        'hello.c'
<command-line>: warning: missing terminating " character
<command-line>: error: missing terminating " character
hello.c:18:2: note: in expansion of macro 'DOCKER_GREETING'
  DOCKER_GREETING "\n"
  ^~~~~~~~~~~~~~~
hello.c:18:18: error: expected ',' or ';' before string constant
  DOCKER_GREETING "\n"
                  ^~~~
make: *** [Makefile:21: amd64/hello-world/hello] Error 1
The command '/bin/sh -c set -ex;        make clean all test             TARGET_ARCH='amd64'  CROSS_COMPILE='x86_64-linux-gnu-'' returned a non-zero code: 2

```
any ideas why the 'make' would have an issue with this variable setting?

Workaround - edit the Makefile and remove the line for "-D DOCKER_GREETING=" and repeat the docker build command.

**Comment by tianon** [comment]
I'm also on Docker 19.03.12, and I'm not able to reproduce with the exact same command.

Have you made any modifications to your local checkout that could be related?

Another way to test without a local checkout (to help narrow down why it's failing) would be `docker build --pull --file Dockerfile.build https://github.com/docker-library/hello-world.git`.

**Comment by caryo** [comment]
Thanks for the suggestion; however, the error occurs in clean working folder and executing only the following command:

$ docker build --pull --file Dockerfile.build https://github.com/docker-library/hello-world.git

I also tried the --no-cache=true with docker build and it still shows the error.

**Comment by tianon** [comment]
Can you provide the output of `docker info` and `docker version`?  This sounds like it could be something weird in your local environment, but it's hard to narrow down (especially since we can't reproduce).

**Comment by caryo** [comment]
Thanks - here's the output you requested:

$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: XZVO:MVIJ:C67W:L6K7:CND2:MVN5:DUCL:3OVV:NYYV:X3NX:GDEW:QXKH
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-09-30T10:04:56.740092324Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

$ docker version
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by caryo** [comment]
I made one small change to the Makefile :

```
diff --git a/Makefile b/Makefile
index 374fda7..577e5dd 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,7 @@ $(C_TARGETS): hello.c $(MUSL_GCC)
        $(MUSL_GCC) $(CFLAGS) -Wl,--gc-sections -static \
                -o '$@' \
                -D DOCKER_IMAGE='"$(notdir $(@D))"' \
-               -D DOCKER_GREETING="\"$$(cat 'greetings/$(notdir $(@D)).txt')\"" \
+               -D DOCKER_GREETING="\"$(shell cat 'greetings/$(notdir $(@D)).txt')\"" \
                -D DOCKER_ARCH='"$(TARGET_ARCH)"' \
                '$<'
        $(STRIP) --s
```

This appears to get past the problem; however, I'm not sure if this is the desired effect.  Can you confirm?  See output below...

```
<snip>
+ make clean all test TARGET_ARCH=amd64 CROSS_COMPILE=x86_64-linux-gnu-
rm -vrf amd64/hello-world/hello /usr/src/hello/musl/amd64
mkdir -p '/usr/src/hello/musl/amd64'
cd '/usr/src/hello/musl/amd64' && '/usr/local/src/musl/configure' --disable-shared --prefix='/usr/src/hello/musl/amd64/prefix' > /dev/null
make -C '/usr/src/hello/musl/amd64' -j '2' install > /dev/null
/usr/src/hello/musl/amd64/prefix/bin/musl-gcc -Os -fdata-sections -ffunction-sections -s -Wl,--gc-sections -static \
        -o 'amd64/hello-world/hello' \
        -D DOCKER_IMAGE='"hello-world"' \
        -D DOCKER_GREETING="\"Hello from Docker!\"" \
        -D DOCKER_ARCH='"amd64"' \
        'hello.c'
x86_64-linux-gnu-strip --strip-all --remove-section=.comment 'amd64/hello-world/hello'
+ ./amd64/hello-world/hello

<snip>

Removing intermediate container 54484a032d1d
 ---> 4baa60e2449f
Step 16/16 : CMD ["./amd64/hello-world/hello"]
 ---> Running in f59e7012e4b4
Removing intermediate container f59e7012e4b4
 ---> 52dc73efc8b2
Successfully built 52dc73efc8b2
Successfully tagged hello-world:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

And re-running locally:

```
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

```

**Comment by tianon** [comment]
Ahhhh, Git for Windows!  If I set `git config --global core.autocrlf true`, I'm able to reproduce the build failure.

I think we can fix this with `.gitattributes`, and I'll be playing with that next. :smile:

**Comment by tianon** [comment]
Got it! https://github.com/docker-library/hello-world/pull/80 :+1:
