### ISSUE TITLE
microk8s on Ubuntu with raspberry 4 hardware (ARMv8)

### ISSUE THREAD

**Issue by 1000ouz** [docker-library/hello-world#81]
I can't make your hello-world run on Ubuntu 20.04.1 LTS with microk8s running on raspberry Pi 4b model (ARMv8)
The pod get created but then "CrashLoopBackOff" forever.
microk8s is using containerd, is there some incompatibility with docker engine for which your image is probably tested/running ?

**Comment by wglambert** [comment]
What do the `kubectl logs` show?

**Comment by 1000ouz** [comment]
I get the "Hello from Docker! ..." when doing kubectl logs, so I suppose it means it works as designed.
From what I understand, the kubernetes pod is restarted because the docker container exits every time it completes its output which forces the pod to restart the container and here we are with a endless "CrashLoopBackOff" status. Is there an option to run the hello-world container as a service and not exit every time ? Cheers

**Comment by yosifkit** [comment]
> Is there an option to run the hello-world container as a service and not exit every time ?

No, the `hello-world` image just prints a message and exits. If you just want a "dummy" service, then something like `docker run -d bash sleep 100000` or `docker run -d busybox httpd -f` or even the `nginx` image should work.
