### ISSUE TITLE
Windows version - bad example

### ISSUE THREAD

**Issue by larryclaman** [docker-library/hello-world#84]
The windows version of hello-world displays:
```
To try something more ambitious, you can run a Windows Server container with:
 PS C:\> docker run -it mcr.microsoft.com/windows/servercore powershell
```
The suggested example doesn't work, as servercore does not supply a latest tag.
I suggest it be modified to read:
`docker run -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell`

**Comment by larryclaman** [comment]
see PR #85 for fix

**Comment by yosifkit** [comment]
Fixed by https://github.com/docker-library/hello-world/pull/85
