### ISSUE TITLE
the docker official image hello-world keep reporting 'Back-off restarting failed container' with kubectl command

### ISSUE THREAD

**Issue by superzc-github** [docker-library/hello-world#87]
Im keep seeing 'Back-off restarting failed container' when try to use docker official image https://hub.docker.com/_/hello-world to create any pod\deployment, switch to other images like 'nginx' everything will work well, Please help, thanks.

both 'last' and 'linux' tag was tried and got same failure for the image

[Event logs for kubectl creation]

root@ip-10-229-68-221:~# kubectl get event --watch LAST SEEN TYPE REASON OBJECT MESSAGE 24s Normal Scheduled pod/helloworld-656898b9bb-98vrv Successfully assigned default/helloworld-656898b9bb-98vrv to kind-lab-worker 23s Normal Pulling pod/helloworld-656898b9bb-98vrv Pulling image "hello-world:linux" 16s Normal Pulled pod/helloworld-656898b9bb-98vrv Successfully pulled image "hello-world:linux" in 7.371731633s 1s Normal Created pod/helloworld-656898b9bb-98vrv Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-98vrv Started container hello-world 1s Normal Pulled pod/helloworld-656898b9bb-98vrv Container image "hello-world:linux" already present on machine 13s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 24s Normal Scheduled pod/helloworld-656898b9bb-sg6fs Successfully assigned default/helloworld-656898b9bb-sg6fs to kind-lab-worker 23s Normal Pulling pod/helloworld-656898b9bb-sg6fs Pulling image "hello-world:linux" 13s Normal Pulled pod/helloworld-656898b9bb-sg6fs Successfully pulled image "hello-world:linux" in 9.661065021s 13s Normal Created pod/helloworld-656898b9bb-sg6fs Created container hello-world 13s Normal Started pod/helloworld-656898b9bb-sg6fs Started container hello-world 13s Normal Pulled pod/helloworld-656898b9bb-sg6fs Container image "hello-world:linux" already present on machine 11s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 24s Normal Scheduled pod/helloworld-656898b9bb-vhhfm Successfully assigned default/helloworld-656898b9bb-vhhfm to kind-lab-worker 23s Normal Pulling pod/helloworld-656898b9bb-vhhfm Pulling image "hello-world:linux" 18s Normal Pulled pod/helloworld-656898b9bb-vhhfm Successfully pulled image "hello-world:linux" in 5.17232683s 3s Normal Created pod/helloworld-656898b9bb-vhhfm Created container hello-world 2s Normal Started pod/helloworld-656898b9bb-vhhfm Started container hello-world 3s Normal Pulled pod/helloworld-656898b9bb-vhhfm Container image "hello-world:linux" already present on machine 2s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 24s Normal SuccessfulCreate replicaset/helloworld-656898b9bb Created pod: helloworld-656898b9bb-vhhfm 24s Normal SuccessfulCreate replicaset/helloworld-656898b9bb Created pod: helloworld-656898b9bb-sg6fs 24s Normal SuccessfulCreate replicaset/helloworld-656898b9bb Created pod: helloworld-656898b9bb-98vrv 24s Normal ScalingReplicaSet deployment/helloworld Scaled up replica set helloworld-656898b9bb to 3 79s Normal Killing pod/nginx Stopping container nginx 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-sg6fs Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-sg6fs Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-sg6fs Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-vhhfm Container image "hello-world:linux" already present on machine 0s Normal Pulled pod/helloworld-656898b9bb-98vrv Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-vhhfm Created container hello-world 1s Normal Created pod/helloworld-656898b9bb-98vrv Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-vhhfm Started container hello-world 0s Normal Started pod/helloworld-656898b9bb-98vrv Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-sg6fs Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-sg6fs Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-sg6fs Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-vhhfm Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-vhhfm Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-vhhfm Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-98vrv Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-98vrv Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-98vrv Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-98vrv Back-off restarting failed container 0s Warning BackOff pod/helloworld-656898b9bb-vhhfm Back-off restarting failed container 0s Normal Pulled pod/helloworld-656898b9bb-sg6fs Container image "hello-world:linux" already present on machine 0s Normal Created pod/helloworld-656898b9bb-sg6fs Created container hello-world 0s Normal Started pod/helloworld-656898b9bb-sg6fs Started container hello-world 0s Warning BackOff pod/helloworld-656898b9bb-sg6fs Back-off restarting failed container

**Comment by tianon** [comment]
This image isn't a service; it's essentially `echo` with a canned message, so what you're seeing is exactly the expected behavior. If you check your pod's logs, you'll probably see the generic "it's working" message over and over again.
