### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by plsnp** [docker-library/hello-world#90]
Could some instructions be added how to build this project into a docker container? I figured out eventually that update.sh was doing some building, which i didn't expect from the name "update".

I used this project as an example project to test my gitlab registry. There i need to build the image with a specific name so it can upload to the registry later. I didn't see an option to build with a specific name (as part of update.sh ?) so i renamed (docker tag) the image afterwards of which i'm also not sure if it's the best way to go.

**Comment by wglambert** [comment]
You just grab the Dockerfile and the `hello` file that's copied in (and adjusting the permissions so it can execute in the container)
https://github.com/docker-library/hello-world/blob/07c029f525763706fde053567bdc63f2e0d98a02/amd64/hello-world/Dockerfile#L2

```console
$ wget https://raw.githubusercontent.com/docker-library/hello-world/master/amd64/hello-world/Dockerfile
Connecting to raw.githubusercontent.com (185.199.108.133:443)
saving to 'Dockerfile'
Dockerfile           100% |*********************************************************|    41  0:00:00 ETA
'Dockerfile' saved

$ wget https://github.com/docker-library/hello-world/raw/master/amd64/hello-world/hello
Connecting to github.com (140.82.113.4:443)
Connecting to raw.githubusercontent.com (185.199.111.133:443)
saving to 'hello'
hello                100% |*********************************************************| 13336  0:00:00 ETA
'hello' saved

$ chmod 777 hello

$ docker build . -t hello-world:test
Sending build context to Docker daemon  47.02MB
Step 1/3 : FROM scratch
 ---> 
Step 2/3 : COPY hello /
 ---> a90955082d7b
Step 3/3 : CMD ["/hello"]
 ---> Running in 15725aae6f65
Removing intermediate container 15725aae6f65
 ---> 1f1ef96ad133
Successfully built 1f1ef96ad133
Successfully tagged hello-world:test

$ docker run hello-world:test

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by plsnp** [comment]
Thanks @wglambert maybe it would be good to put something in the readme about this ?

**Comment by tianon** [comment]
This repository exists as the source for https://hub.docker.com/_/hello-world -- we don't really encourage or directly support users building it themselves, so some amount of Yak shaving for users who want/need to is (unfortunately) expected.

**Comment by BillKanawyer** [comment]
@tianon:  Your observation, Yak shaving aside, is not strictly accurate.  Please  review [Create a simple parent image using scratch](https://docs.docker.com/develop/develop-images/baseimages/#create-a-simple-parent-image-using-scratch) which does indeed encourage Docker students to look at hello-world sources for instructions.  It says in part: 

"Assuming you built the “hello” executable example by following the instructions at https://github.com/docker-library/hello-world/, and ...". 

It seems reasonable to me there should be some information, possibly including a disclaimer of "no support", that amount to instructions for use.  Therefore I respectfully second @plsnp request.

**Comment by tianon** [comment]
It wasn't an observation, but a statement of maintainer intent as the creator and maintainer of this repository :sweat_smile:

I've filed https://github.com/docker/docker.github.io/pull/13131 to try and improve that documentation to no longer imply we provide instructions for building within this repository.

**Comment by tianon** [comment]
(That being said, there is a `Dockerfile.build` which canonically gets built by `update.sh` to include `Makefile` and `hello.c` for building the canonical binaries across all architectures -- the number of architectures we support makes this necessarily complicated.)
